const problemes = [
  {
    id: 1,
    categorie: "problème",
    autheur: "Bernard Delobel",
    annee: 2014,
    ref: "aac",
    intro: "<p><b>Hello</b>, vois mon problème.</p>",
    fenPosition: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
    nbCoups: 2,
    infos: "info",
    solution: "<p>ici la solution <b>Cf3->Cd2</b></p>",
  },
  {
    id: 2,
    categorie: "catégorie 2",
    autheur: "Christophe Delobel",
    annee: 2021,
    ref: null,
    intro: "<p><b>Bonjour !</b></p>",
    fenPosition: "8/3q1b2/6p1/8/8/3Q4/3R4/2K5",
    nbCoups: 4,
    infos: null,
    solution: "<p>En fait pas de solution</p>",
  },
  {
    id: 3,
    categorie: "catégorie 3",
    autheur: "Julie Delobel",
    annee: 2021,
    ref: null,
    intro: "<p><b>Bonjour !</b></p>",
    fenPosition: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
    nbCoups: 4,
    infos: null,
    solution: "<p>En fait pas de solution</p>",
  },
  {
    id: 4,
    categorie: "catégorie 3",
    autheur: "Maya Delobel",
    annee: 2019,
    ref: null,
    intro: "<p><b>Bonjour !</b></p>",
    fenPosition: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR",
    nbCoups: 8,
    infos: null,
    solution: "<p>En fait pas de solution</p>",
  },
];
export default problemes;
